#!/bin/sh
# $FreeBSD: head/print/texinfo/pkg-install 340719 2014-01-22 15:52:06Z mat $

[ $# != 2 ] && exit 1
PKGNAME=$1
ACTION=$2

PATH="${PKG_PREFIX}/bin:${LOCALBASE}/bin:/usr/bin:${PATH}"

SETENV=env
TEXHASH=texhash
TRUE=true

case "$ACTION" in

POST-INSTALL|DEINSTALL)
	${SETENV} PATH="${PATH}" ${TEXHASH} 2>/dev/null || ${TRUE}
	;;

PRE-INSTALL|POST-DEINSTALL)
	;;

*)
	exit 1
	;;
esac

exit
