# $FreeBSD: head/devel/automake-wrapper/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	automake-wrapper

COMMENT=	Wrapper script for GNU automake

MASTERDIR=	${.CURDIR}/../../devel/autoconf-wrapper
PKGDIR=		${.CURDIR}

TOOL=		AUTOMAKE
WRAPPED_TOOLS=	aclocal automake

.include "${MASTERDIR}/Makefile"
