# $FreeBSD: head/devel/gettext/Makefile 386359 2015-05-14 20:22:03Z bapt $

# NOTE: before committing to this port, contact portmgr to arrange for an
# experimental ports run.  Untested commits may be backed out at portmgr's
# discretion.

PORTNAME=	gettext
PORTREVISION=	0

COMMENT=	GNU gettext meta package

.include "${.CURDIR}/../gettext/Makefile.common"

USES=		gettext-runtime:run gettext-tools:run metaport

.include <bsd.port.mk>
