# Mk/Uses/python.mk includes this file, don't remove it!
# $FreeBSD: head/lang/python37/Makefile.version 528692 2020-03-19 07:18:35Z wen $

# Do not forget to update python documentation (lang/python-doc-*)
# Run "make -C lang/python-doc-html makesum"
PYTHON_PORTVERSION=	3.7.7
