SUBDIR += pkg
SUBDIR += poudriere-devel
SUBDIR += poudriere-devel-dep-IGNORED
SUBDIR += poudriere-devel-dep2-IGNORED
SUBDIR += poudriere-devel-IGNORED-and-skipped
SUBDIR += poudriere-devel-IGNORED
# Would break bulk -a test
#SUBDIR += poudriere-devel-bad-dep_args
SUBDIR += poudriere-devel-dep-DEFAULT
SUBDIR += poudriere-devel-dep-FOO
# Would break bulk -a test
#SUBDIR += poudriere-devel-dep-INVALID
SUBDIR += yyyy
SUBDIR += zzzz
