SUBDIR += pkg
SUBDIR += poudriere-devel
# Would break bulk -a test
#SUBDIR += poudriere-devel-bad-dep_args
SUBDIR += poudriere-devel-dep-DEFAULT
SUBDIR += poudriere-devel-dep-FOO
# Would break bulk -a test
#SUBDIR += poudriere-devel-dep-INVALID
