#!/bin/sh
#
# $FreeBSD: head/Mk/Wrappers/bison 528174 2020-03-10 14:22:50Z bapt $

# This wrappers allows to deals build system calling bison with certain long option
# and messing with arguments orders

case " $@ " in
*" --version "*) echo "bison (GNU bison 3.5.2)" ; exit 0 ;;
esac

for arg; do
	case "$arg" in
	*.y) inputfile="$arg" ;;
	--verbose|-v) ;; # ignore
	*) args="$args $arg" ;;
	esac
done
exec byacc $args $inputfile
